dist: trusty
language: java
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
       - $HOME/.m2
env:
  global:
    - DISPLAY=:99.0
  dist: xenial

script:
  - mvn test -f ./pom.xml

after_success:
  - mvn clean test cobertura:cobertura coveralls:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vicboma1_Microservices-SpringBoot-ReactorCore
  
addons:
  sonarcloud:
    organization: "vicboma1" # the key of the org you chose at step #3
    token:
      secure: "a9ee7bc9639baa51a57b817f575cd53a1e96de35" # encrypted value of your token
