dist: trusty
language: java
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
       - $HOME/.m2

env:
  global:
    - DISPLAY=:99.0
  dist: xenial

script:
  - mvn test -f ./pom.xml

after_success:
  - mvn clean test cobertura:cobertura coveralls:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vicboma1_pattern-design
  
addons:
  sonarcloud:
    organization: "vicboma1" # the key of the org you chose at step #3
    token:
      secure: "2fb0bd87ddc7987a9c95027e1433c659091c29d0" # encrypted value of your token
